from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static

from django.conf import settings
urlpatterns = [
    path('', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('home/',views.home, name='home'),
    path('destinations/',views.destinations,name='destinations'),
    path('kanakadurga/',views.kanakadurga,name='kanakadurga'),
    path('machilipatnam/',views.machilipatnam,name='machilipatnam'),
    path('kondapalli/',views.kondapalli, name='kondapalli'),
    path('bhavani island/',views.bhavaniisland, name='bhavaniisland'),
    path('vijayawada/',views.vijayawada, name='vijayawada'),
    path('gandhihill/',views.gandhihill, name='gandhihill'),
    path('kuchipudi/',views.kuchipudi, name='kuchipudi'),
    path('prakasam barrage/',views.prakasambarrage, name='prakasambarrage'),
    path('coringa wildlife/',views.coringawildlife, name='coringawildlife'),
    path('papikondalu/',views.papikondalu, name='papikondalu'),
    path('annavaram/',views.annavaram, name='annavaram'),
    path('rajahmundry/',views.rajahmundry, name='rajahmundry'),
    path('draksharamam/',views.draksharamam, name='draksharamam'),
    path('dindi/',views.dindi, name='dindi'),
    path('maredumilli/',views.maredumilli, name='maredumilli'),
    path('godavari bridge/',views.godavaribridge, name='godavaribridge'),
    path('kailasagiri hills/',views.kailasagirihills, name='kailasagirihills'),
    path('rushikonda/',views.rushikonda, name='rushikonda'),
    path('lambasingi/',views.lambasingi, name='lambasingi'),
    path('borra caves/',views.borracaves, name='borracaves'),
    path('bheemili beach/',views.bheemilibeach, name='bheemilibeach'),
    path('submarine museum/',views.submarinemuseum, name='submarinemuseum'),
    path('araku/',views.araku, name='araku'),
    path('simhachalam/',views.simhachalam, name='simhachalam'),
    path('gooty fort/',views.gootyfort, name='gootyfort'),
    path('lepakshi/',views.lepakshi, name='lepakshi'),
    path('thimmamma marrimaanu/',views.thimmamma, name='thimmamma'),
    path('hemavathi temple/',views.hemavathi, name='hemavathi'),
    path('penukonda fort/',views.penukonda, name='penukonda'),
    path('kadiri lakshmi narasimha swamy temple/',views.klns, name='klns'),
    path('Bugga ramalingeswara swamy temple/',views.brs, name='brs'),
    path('chintala venkataramana swamy temple/',views.cvs, name='cvs'),
    path('pedakakani/',views.pedakakani, name='pedakakani'),
    path('mahachaitya amaravathi/',views.amaravathi, name='amaravathi'),
    path('chebrole/',views.chebrole, name='chebrole'),
    path('mangalagiri/',views.mangalagiri, name='mangalagiri'),
    path('undavalli caves/',views.undavalli, name='undavalli'),
    path('ettipotala waterfalls/',views.ettipotala, name='ettipotala'),
    path('uppalapadu bird scanctuary/',views.uppalapadu, name='uppalapadu'),
    path('dhyana buddha statue/',views.dhyana, name='dhyana'),
    path('feedback/',views.feedback, name='feedback'),
    path('feedback success/',views.feedback1, name='feedback1'),
    path('gallerypage/',views.gallerypage, name='gallerypage'),
    path('contactus/',views.contactus, name='contact us'),
    path('categories/',views.categories, name='categories'),
]

